In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from selenium import webdriver
from bs4 import BeautifulSoup
import re
import scrapy
import urllib
import json
import time

#Data Preprocessing and Feature Engineering
from textblob import TextBlob
from nltk import tokenize
import re
from textblob import Word
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

#FindingPolarity
from nltk.sentiment.vader import SentimentIntensityAnalyzer

D:\Anaconda\lib\site-packages\nltk\twitter\__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "

In [ ]:
driver = webdriver.Chrome("C:\\Users\\humai\\chromedriver")
driver.get("https://www.imdb.com/showtimes/location?ref_=sh_lc")
content = driver.page_source
soup = BeautifulSoup(content)

In [ ]:
list_of_movies = []
for a in soup.findAll('div',attrs={'class':'lister-item mode-grid'}):
    movie_name = a.find('div',attrs={'class','title'})
    list_of_movies.append(movie_name)
#     print(movie_name)
movie_show_links = []
for i in range(len(list_of_movies)):
#     print(list_of_movies[i].a["href"])
    link = "https://www.imdb.com" + list_of_movies[i].a["href"] #https:// is needed
    print(link)
    movie_show_links.append(link)
driver.quit()

In [ ]:
driver = webdriver.Chrome("C:\\Users\\humai\\chromedriver")
movie_link = []
for movie_show_link in movie_show_links:
    driver.get(movie_show_link)
    content = driver.page_source
    soup = BeautifulSoup(content)
    for a in soup.findAll('td',attrs = {'class','overview-top'}):
        movie_link.append("https://www.imdb.com" + a.find('a')['href'])
driver.quit()

In [ ]:
len(movie_show_links)

# HAVE TO GET THE USER REVIEW LINKS

In [ ]:
driver = webdriver.Chrome("C:\\Users\\humai\\chromedriver")
review_links = []
for link in movie_link:
    driver.get(link)
    time.sleep(1)
    content = driver.page_source
    soup = BeautifulSoup(content)
    for a in soup.findAll('div',attrs = {'class','user-comments'}):
        temp = a.findAll('a')[-1]["href"]
        print(temp)
        review_links.append(temp)
    for a in soup.findAll('div',attrs = {'class','user-comments'}):
        temp = a.findAll('a')[-1]["href"]
        print(temp)
        review_links.append(temp)
    time.sleep(2)
driver.quit()

In [ ]:
len(review_links)

# Collecting reviews of all the movies listed

TRYING TO COLLECT ALL USER REVIEWS FOR ONE MOVIE THEN WE CAN CLUB IT TO THE LINKS WHICH WE COLLECTED ABOVE
PROPER STRUCTURING IS NEEDED AT THE END

In [3]:
start = time.time()

driver = webdriver.Chrome("C:\\Users\\humai\\chromedriver")
url =  'https://www.imdb.com/title/tt6751668/reviews?ref_=tt_urv' #DOING FOR ONE PARTICULAR FILM
driver.get(url)

while True:
    try:
        loadmore = driver.find_element_by_id("load-more-trigger")
        print(loadmore)
        time.sleep(3)
        loadmore.click()
        time.sleep(3)        
    except:
        print("DONEEE")
        break

#Load more button clicked repeatedly
content = driver.page_source
soup = BeautifulSoup(content,'lxml')
reviews = []
for a in soup.findAll('div',attrs ={'class','text show-more__control'}):
    reviews.append(a.text)

end = time.time()
print(end - start)
driver.quit()

<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
<selenium.webdriver.remote.webelement.WebElement (session="7e252affb50bf45a5c2b0ad92f38e0e3", element="96423cf5-613a-47d1-8089-6cb3402fa8d4")>
DONEEE
431.9077386856079

Couldnt get all the reviews. Have to add all possible classes to get that text.

In [4]:
len(reviews)

1440

# Adding metrics to DF

In [5]:
df = pd.DataFrame(np.array(reviews),columns=["reviews"])

In [6]:
#WordCount
df['word_count'] = df['reviews'].apply(lambda x: len(x.split()))
df.head()

                                             reviews  word_count
0  It's not really a review but my attempt to exp...         778
1  This movie is a gosh darn masterpiece. It will...          51
2  This is a well written and well perfomed origi...          64
3  Well written and performed also technically sh...          70
4  "It's so metaphorical" is what Kevin says when...         543

In [7]:
#Character count
df['char_count'] = df['reviews'].apply(lambda x : len(x))
df.head()

                                             reviews  word_count  char_count
0  It's not really a review but my attempt to exp...         778        4538
1  This movie is a gosh darn masterpiece. It will...          51         260
2  This is a well written and well perfomed origi...          64         387
3  Well written and performed also technically sh...          70         436
4  "It's so metaphorical" is what Kevin says when...         543        3038

In [8]:
#average length of each word inside the review
def average_words(x):
    words = x.split()
    return sum(len(word) for word in words) / len(words)
df['average_word_length'] = df['reviews'].apply(average_words)
df.head()

,reviews,word_count,char_count,average_word_length
0,It's not really a review but my attempt to exp...,778,4538,4.834190
1,This movie is a gosh darn masterpiece. It will...,51,260,4.117647
2,This is a well written and well perfomed origi...,64,387,5.062500
3,Well written and performed also technically sh...,70,436,5.242857
4,"""It's so metaphorical"" is what Kevin says when...",543,3038,4.596685

In [9]:
#Stopwordcount
stop_words = stopwords.words('english')

In [10]:
#Find how many stopwwords are there in each review
df['stopword_count'] = df['reviews'].apply(lambda x:len([word for word in x.split() if word.lower() in stop_words]))
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count
0,It's not really a review but my attempt to exp...,778,4538,4.834190,360
1,This movie is a gosh darn masterpiece. It will...,51,260,4.117647,28
2,This is a well written and well perfomed origi...,64,387,5.062500,24
3,Well written and performed also technically sh...,70,436,5.242857,24
4,"""It's so metaphorical"" is what Kevin says when...",543,3038,4.596685,277

In [11]:
#Stopword Rate
df['stopword_rate'] = df['stopword_count']/df['word_count']
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate
0,It's not really a review but my attempt to exp...,778,4538,4.834190,360,0.462725
1,This movie is a gosh darn masterpiece. It will...,51,260,4.117647,28,0.549020
2,This is a well written and well perfomed origi...,64,387,5.062500,24,0.375000
3,Well written and performed also technically sh...,70,436,5.242857,24,0.342857
4,"""It's so metaphorical"" is what Kevin says when...",543,3038,4.596685,277,0.510129

In [12]:
df.describe()

,word_count,char_count,average_word_length,stopword_count,stopword_rate
count,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000
mean,98.794444,557.026389,4.655121,46.279167,0.455159
std,145.401309,837.297056,0.566005,67.904615,0.082992
min,5.000000,34.000000,3.169811,0.000000,0.000000
25%,32.000000,180.750000,4.328472,14.000000,0.416667
50%,61.000000,346.000000,4.579877,29.000000,0.464286
75%,109.000000,608.000000,4.887169,52.000000,0.506494
max,1533.000000,9632.000000,11.243902,742.000000,0.764706

# DATA CLEANING

In [13]:
#Lowering the case
df['lowercase'] = df['reviews'].apply(lambda x: " ".join(word.lower() for word in x.split()))
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,lowercase
0,It's not really a review but my attempt to exp...,778,4538,4.834190,360,0.462725,it's not really a review but my attempt to exp...
1,This movie is a gosh darn masterpiece. It will...,51,260,4.117647,28,0.549020,this movie is a gosh darn masterpiece. it will...
2,This is a well written and well perfomed origi...,64,387,5.062500,24,0.375000,this is a well written and well perfomed origi...
3,Well written and performed also technically sh...,70,436,5.242857,24,0.342857,well written and performed also technically sh...
4,"""It's so metaphorical"" is what Kevin says when...",543,3038,4.596685,277,0.510129,"""it's so metaphorical"" is what kevin says when..."

In [15]:
#Removing punctuations
def rem_punc(review):
    review_blob = TextBlob(review)
    return ' '.join(review_blob.words)
df['punctuation'] = df['lowercase'].apply(rem_punc)

In [16]:
#REMOVING STOPWORDS AND UNUSUAL SYMBOLS
def rem_stop_sym(review):
        review_list = [ele for ele in review.split()]
        clean_tokens = [t for t in review_list if re.match(r'[^\W\d)]*$',t)]
        clean_s = ' '.join(clean_tokens)
        clean_review = [word for word in clean_s.split() if word.lower() not in stopwords.words('english')]
        return " ".join(clean_review)
df['stopword'] = df['punctuation'].apply(rem_stop_sym)

In [17]:
pd.Series(" ".join(df['stopword']).split()).value_counts()[:30]

movie       1772
film        1253
family       749
one          619
like         549
parasite     522
best         490
good         471
story        405
really       386
poor         369
rich         367
people       341
watch        338
well         323
great        321
movies       312
way          308
get          305
would        292
even         267
see          265
first        259
bong         253
plot         244
class        243
time         242
korean       237
many         235
think        231
dtype: int64

In [18]:
#Removing the words that do not contribute to the Sentiment Analysis
other_stopwords = ['also','like','get','would','one','even','way']
df['cleanreviews'] = df['stopword'].apply(lambda x: " ".join(word for word in x.split() if word not in other_stopwords))
df.head()
#Add other stopwords by repeating the pd.Series statement again for next 30 and so on

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,lowercase,punctuation,stopword,cleanreviews
0,It's not really a review but my attempt to exp...,778,4538,4.834190,360,0.462725,it's not really a review but my attempt to exp...,it 's not really a review but my attempt to ex...,really review attempt explain interpreted movi...,really review attempt explain interpreted movi...
1,This movie is a gosh darn masterpiece. It will...,51,260,4.117647,28,0.549020,this movie is a gosh darn masterpiece. it will...,this movie is a gosh darn masterpiece it will ...,movie gosh darn masterpiece make belly laugh c...,movie gosh darn masterpiece make belly laugh c...
2,This is a well written and well perfomed origi...,64,387,5.062500,24,0.375000,this is a well written and well perfomed origi...,this is a well written and well perfomed origi...,well written well perfomed original film lot r...,well written well perfomed original film lot r...
3,Well written and performed also technically sh...,70,436,5.242857,24,0.342857,well written and performed also technically sh...,well written and performed also technically sh...,well written performed also technically shines...,well written performed technically shines cine...
4,"""It's so metaphorical"" is what Kevin says when...",543,3038,4.596685,277,0.510129,"""it's so metaphorical"" is what kevin says when...",it 's so metaphorical is what kevin says when ...,metaphorical kevin says show paint makes state...,metaphorical kevin says show paint makes state...

# Lemmatization

In [19]:
df['lemmatized'] = df['cleanreviews'].apply(lambda x: " ".join(Word(word).lemmatize() for word in x.split()))
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,lowercase,punctuation,stopword,cleanreviews,lemmatized
0,It's not really a review but my attempt to exp...,778,4538,4.834190,360,0.462725,it's not really a review but my attempt to exp...,it 's not really a review but my attempt to ex...,really review attempt explain interpreted movi...,really review attempt explain interpreted movi...,really review attempt explain interpreted movi...
1,This movie is a gosh darn masterpiece. It will...,51,260,4.117647,28,0.549020,this movie is a gosh darn masterpiece. it will...,this movie is a gosh darn masterpiece it will ...,movie gosh darn masterpiece make belly laugh c...,movie gosh darn masterpiece make belly laugh c...,movie gosh darn masterpiece make belly laugh c...
2,This is a well written and well perfomed origi...,64,387,5.062500,24,0.375000,this is a well written and well perfomed origi...,this is a well written and well perfomed origi...,well written well perfomed original film lot r...,well written well perfomed original film lot r...,well written well perfomed original film lot r...
3,Well written and performed also technically sh...,70,436,5.242857,24,0.342857,well written and performed also technically sh...,well written and performed also technically sh...,well written performed also technically shines...,well written performed technically shines cine...,well written performed technically shine cinem...
4,"""It's so metaphorical"" is what Kevin says when...",543,3038,4.596685,277,0.510129,"""it's so metaphorical"" is what kevin says when...",it 's so metaphorical is what kevin says when ...,metaphorical kevin says show paint makes state...,metaphorical kevin says show paint makes state...,metaphorical kevin say show paint make stateme...

# Sentiment Analysis

In [20]:
from textblob import TextBlob

In [23]:
df['polarity'],df['subjectivity'] = df['lemmatized'].apply(lambda x: TextBlob(x).sentiment[0]),df['lemmatized'].apply(lambda x: TextBlob(x).sentiment[1])

In [25]:
df.drop(['lowercase','punctuation','stopword','cleanreviews','lemmatized'],axis =1)

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,polarity,subjectivity
0,It's not really a review but my attempt to exp...,778,4538,4.834190,360,0.462725,0.086556,0.453222
1,This movie is a gosh darn masterpiece. It will...,51,260,4.117647,28,0.549020,0.125000,0.250000
2,This is a well written and well perfomed origi...,64,387,5.062500,24,0.375000,0.144781,0.442172
3,Well written and performed also technically sh...,70,436,5.242857,24,0.342857,0.421627,0.455357
4,"""It's so metaphorical"" is what Kevin says when...",543,3038,4.596685,277,0.510129,0.169878,0.555969
5,Do you want to see a movie that will have your...,146,805,4.520548,73,0.500000,0.036111,0.488889
6,Most of the time when my opinion does not jibe...,59,317,4.389831,36,0.610169,0.246259,0.570522
7,Finally saw this much talked about film. As a ...,90,533,4.933333,35,0.388889,0.112889,0.720444
8,This movie is so masterfully written and prese...,173,989,4.722543,80,0.462428,0.132950,0.592018
9,I thought I knew what was happening but it tur...,54,277,4.148148,25,0.462963,0.062500,0.271131
10,"Well what can I say, Boong Joon-Ho is truly de...",52,300,4.788462,27,0.519231,0.190000,0.827778
11,"Parasite (Gisaengchung), the 2019 film by Bong...",144,834,4.798611,65,0.451389,-0.014935,0.475397
12,Parasite is a true work of art and a rare and ...,167,898,4.383234,87,0.520958,0.123320,0.613043
13,I don't watch many non-english language films ...,111,638,4.756757,55,0.495495,0.202083,0.411012
14,Bong Joo Ho has been making ingenious social c...,105,617,4.885714,55,0.523810,0.282645,0.548209
15,"Here's how i rate a movie the fast way, i ask ...",135,718,4.325926,69,0.511111,0.051786,0.558011
16,The film is ok but that's as far as I go. It's...,64,299,3.687500,36,0.562500,0.580000,0.720000
17,'Parasite - an organism that lives in or on an...,151,916,5.072848,67,0.443709,0.225833,0.508333
18,I felt a roller coaster of emotions watching t...,60,332,4.550000,29,0.483333,0.660000,0.680000
19,What an amazing film! Clearly an essay on the ...,131,758,4.793893,56,0.427481,0.022377,0.431944
20,There is no shortage of films that depict the ...,412,2563,5.223301,179,0.434466,0.058678,0.523960
21,"Director Bong Joon-ho's global sensation, Para...",88,553,5.295455,35,0.397727,0.101731,0.503077
22,This film shows humanity in all its glory. We ...,98,518,4.295918,49,0.500000,-0.017708,0.612500
23,"Good movie, interesting story line, but never ...",31,183,4.935484,11,0.354839,0.392045,0.536111
24,Parasite: A con-artist family preys on an uppe...,190,1055,4.557895,90,0.473684,0.174242,0.410606
25,"One of my best films, rarely comes across such...",38,216,4.710526,15,0.394737,0.666667,0.683333
26,I watched this movie (before Oscars) and I kno...,42,234,4.595238,17,0.404762,0.750000,0.594444
27,Apart from the great cinematography what overw...,64,368,4.765625,32,0.500000,0.240000,0.470000
28,"Just watched this film yesterday, really love ...",16,104,5.562500,5,0.312500,0.300000,0.750000
29,"Exceptionally written, ingeniously directed, a...",62,427,5.903226,24,0.387097,0.243750,0.762500
...,...,...,...,...,...,...,...,...
1410,It's like taking steps to reach the top! The c...,14,73,4.285714,5,0.357143,0.500000,0.500000
1411,Great film - one of the best in the last coupl...,13,56,3.384615,5,0.384615,0.600000,0.372222
1412,"A movie with stakes, set ups and payoffs and a...",12,62,4.250000,5,0.416667,0.400000,0.700000
1413,That sums up it all. When the characters seem ...,42,203,3.857143,24,0.571429,0.233333,0.633333
1414,"Great sample of 9 stars movie: plot, acting, s...",23,147,5.434783,7,0.304348,0.153125,0.412500
1415,One that will leave you thinking\nOne that wil...,12,65,4.500000,6,0.500000,0.000000,0.000000
1416,It was the most mysterious film I've seen in a...,25,129,4.200000,12,0.480000,0.100000,0.650000
1417,Not sure about it being the masterpiece that a...,69,412,4.985507,29,0.420290,0.212821,0.633761
1418,A good Movie. A Little to Long but definetly w...,15,82,4.533333,6,0.400000,0.202500,0.520000
1419,"Directed by Bong Joon Ho, i had high hopes for...",109,597,4.486239,57,0.522936,0.396364,0.533939
1420,"It's a layered, complex film sans any heavy-ha...",24,158,5.625000,10,0.416667,-0.066667,0.733333
1421,Bong Joon Ho is an absolute genius and has str...,132,758,4.750000,63,0.477273,0.224074,0.546142
1422,I'll keep it short.This is one of the two best...,127,688,4.425197,58,0.456693,0.279167,0.561111
1423,"Many dialogues are impressive, like a spear st...",10,62,5.300000,3,0.300000,0.300000,0.766667
1424,"Happening once every dacade , strong story , a...",15,84,4.666667,4,0.266667,0.433333,0.558333
1425,There's a lot to Parasite. A very complex stor...,111,631,4.693694,51,0.459459,0.220312,0.448177
1426,This is a good movie which contains many metap...,87,466,4.367816,45,0.517241,0.099915,0.588435
1427,Great acting and beautiful camera. Surprising ...,38,232,5.131579,13,0.342105,0.327778,0.682099
1428,"While set in Korea, the main theme of this mov...",380,2217,4.836842,175,0.460526,0.128122,0.486712
1429,I thought was it was one of the best films for...,119,697,4.865546,54,0.453782,0.058333,0.493333
1430,"This is one of the best movies of this year , ...",70,344,3.928571,38,0.542857,0.551429,0.705714
1431,Wow. A truly exceptional film that somehow liv...,142,891,5.281690,55,0.387324,0.201905,0.674286
1432,There's an unmatched clarity and precision to ...,43,272,5.348837,12,0.279070,0.308333,0.475000
1433,"Slow burn, gripping, tension and feeling uneas...",91,519,4.714286,46,0.505495,0.385714,0.371429
1434,"There is a big hype about this movie, and for ...",125,723,4.792000,61,0.488000,0.251889,0.510256
1435,"This movie was not at all what I expected, whi...",104,549,4.288462,50,0.480769,0.441026,0.478205
1436,Everything is almost perfect from start to fin...,69,385,4.594203,34,0.492754,0.553571,0.560714
1437,"This is a great film, it made me laugh, it mad...",80,430,4.387500,44,0.550000,0.506250,0.650000
1438,The hype behind this film is unbelievable. I'v...,75,424,4.666667,32,0.426667,0.018182,0.640909
1439,This was a rollercosdter from start to finish....,95,506,4.336842,50,0.526316,0.065625,0.601389

In [28]:
pos_count = 0
neg_count = 0
def posnegcount(x):
    global pos_count
    global neg_count
    if(x > 0):
        pos_count = pos_count + 1
    else:
        neg_count = neg_count + 1
df['polarity'].apply(posnegcount)

0       None
1       None
2       None
3       None
4       None
5       None
6       None
7       None
8       None
9       None
10      None
11      None
12      None
13      None
14      None
15      None
16      None
17      None
18      None
19      None
20      None
21      None
22      None
23      None
24      None
25      None
26      None
27      None
28      None
29      None
        ...
1410    None
1411    None
1412    None
1413    None
1414    None
1415    None
1416    None
1417    None
1418    None
1419    None
1420    None
1421    None
1422    None
1423    None
1424    None
1425    None
1426    None
1427    None
1428    None
1429    None
1430    None
1431    None
1432    None
1433    None
1434    None
1435    None
1436    None
1437    None
1438    None
1439    None
Name: polarity, Length: 1440, dtype: object

In [30]:
print(pos_count,neg_count)

1206 234

# Roug

In [44]:
def text_processing(tweet):
    #Removing punctuations
    def rem_punc(tweet):
        tweet_blob = TextBlob(tweet)
        return ' '.join(tweet_blob.words)
    no_punc_tweet = rem_punc(tweet)
    
    #Removing stopwords and unusual symbols
    def rem_stop_sym(tweet):
        tweet_list = [ele for ele in tweet.split() if ele != 'user']
        clean_tokens = [t for t in tweet_list if re.match(r'[^\W\d)]*$',t)]
        clean_s = ' '.join(clean_tokens)
        clean_mess = [word for word in clean_s.split() if word.lower() not in stopwords.words('english')]
        return clean_mess

#     #Normalization
#     def normalization(tweet_list):
#         lem = WordNetLemmatizer()
#         normalized_tweet = []
#         for word in tweet_list:
#             normalized_text = lem.lemmatize(word,'v')
#             normalized_tweet.append(normalized_text)
#         return normalized_tweet
#     return normalization(no_stop_tweet)
    return ' '.join(no_stop_tweet)

In [45]:
text_processing(reviews[0])

'really review attempt explain interpreted movie complain film overrated especially reason like second half much easier understand message movie guys win guys get punished end saying Hollywood films naive portrayal moral values still believe Parasite much subtle movies people accustomed watching character clearer center audiences easily relate think surprise message film failed register complained understand motive killing Mr Park fully appreciate need understand meaning recurring expression dialogue crossing line deliberately ambiguous phrase either read one respect people privacy one mind one social position instead meddling affairs different position interpreted latter meaning serve another image emphasizes subject matter narrative along easy notice metaphor two families respective would probably satisfied audiences expected lighthearted drama movie focused underprivileged likable family exploiting cold hearted snobbish family comical manner movie would lost genuine charms Bong chose path good director see chose make Mr Park reasonable enough character despite occasional hints reveal true nature seems treat fairly enough first also warns latter line attempts pry private first seems quite easy members family sneak Mr Park house various roles mingle even compliments nice Mr Park family premature admiration soon gets challenged overheard hiding table Mr Park really thinks almost different species human even smell like final disillusionment came Mr Park cringes smell dead basement dweller shows much concern son shock virtually ignoring daughter status dying ground spurting blood stab moment realizes Mr Park sees whole family equal human something much also realizes separates two families courtesy proper social behaviour Instead line even determine life human beings less important passing unpleasant feelings mental shock human easy family sneak Mr Park house however try socialize mingle Mr Park family existence better also visualized effectively presence hidden basement room inside disillusionment anger chose kill Mr Park parasite could host like parasite keeps hiding deep inside dead host body could claim whole carcass use nourishment tragedy something caused exceptional defect vice either Mr Park personalities Instead drawn invisible hand separating classes according respective social conditions brutal able deprive two families humanity contrasting manners believe message film trying course every movie must make commentary society rather providing pastime everyone without movie change gear second half shed light serious inherent problem society would another heist gone wrong type comedy instead deserving candidate called best film year'

In [46]:
sid = SentimentIntensityAnalyzer()
sid.polarity_scores(text_processing(reviews[0]))

{'neg': 0.184, 'neu': 0.627, 'pos': 0.19, 'compound': -0.0519}

In [31]:
#reviews[0]

In [53]:
lines_list = tokenize.sent_tokenize(reviews[0])

In [ ]:
for sentence in lines_list:
    print(sentence)
    ss = sid.polarity_scores(sentence)
    for k in sorted(ss):
        print('{0}: {1}, '.format(k, ss[k]), end='')
        print()

In [56]:
sid.polarity_scores(reviews[0])

{'neg': 0.151, 'neu': 0.723, 'pos': 0.126, 'compound': -0.9799}

In [58]:
TextBlob(reviews[0]).sentiment

Sentiment(polarity=0.09052631578947366, subjectivity=0.45684210526315794)

In [ ]:
for i in range(len(reviews)): 
    print(TextBlob(text_processing(reviews[i])).sentiment)